// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpLKQ3MK-DJH_xoCYsc8gSR_qCLmjRTY4',
    appId: '1:990552844901:web:b932e43db2a2f02933f48c',
    messagingSenderId: '990552844901',
    projectId: 't-rexy-7f2a7',
    authDomain: 't-rexy-7f2a7.firebaseapp.com',
    storageBucket: 't-rexy-7f2a7.firebasestorage.app',
    measurementId: 'G-KT7Z6PKDD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM6l9Pb_yq3Tf1cPj0zLNqXWsvtMBDnFI',
    appId: '1:990552844901:android:6c49acbd51b3f90633f48c',
    messagingSenderId: '990552844901',
    projectId: 't-rexy-7f2a7',
    storageBucket: 't-rexy-7f2a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwA8AMC4ZuOZ3pYw6tvwST2-Hlpqo7bc',
    appId: '1:990552844901:ios:3bf0de36dde25b7a33f48c',
    messagingSenderId: '990552844901',
    projectId: 't-rexy-7f2a7',
    storageBucket: 't-rexy-7f2a7.firebasestorage.app',
    iosBundleId: 'com.example.trexyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwA8AMC4ZuOZ3pYw6tvwST2-Hlpqo7bc',
    appId: '1:990552844901:ios:3bf0de36dde25b7a33f48c',
    messagingSenderId: '990552844901',
    projectId: 't-rexy-7f2a7',
    storageBucket: 't-rexy-7f2a7.firebasestorage.app',
    iosBundleId: 'com.example.trexyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpLKQ3MK-DJH_xoCYsc8gSR_qCLmjRTY4',
    appId: '1:990552844901:web:3ab828067850306f33f48c',
    messagingSenderId: '990552844901',
    projectId: 't-rexy-7f2a7',
    authDomain: 't-rexy-7f2a7.firebaseapp.com',
    storageBucket: 't-rexy-7f2a7.firebasestorage.app',
    measurementId: 'G-5DZFTJ7SEK',
  );
}
